on-unmatched = "debug"

[formatter.nix]
command = "nixfmt"
options = []
includes = [ "*.nix" ]
excludes = []

[formatter.lua]
command = "stylua"
options = []
includes = [ "*.lua" ]
excludes = []

[formatter.sh]
command = "shfmt"
options = [ "-w", "-i", "4" ]
includes = [ "*.sh" ]
