on-unmatched = "debug"

[formatter.nix]
command = "nixfmt"
options = []
includes = [ "*.nix" ]

[formatter.lua]
command = "stylua"
options = []
includes = [ "*.lua" ]

[formatter.sh]
command = "shfmt"
options = [ "-w", "-i", "4", "-s" ]
includes = [ "*.sh" ]

[formatter.python]
command = "ruff"
options = [ "format" ]
includes = [ "*.py" ]
